name: 'jaffle_shop'
profile: 'jaffle_shop'

#models:
  # Config indicated by + applies to all files under models/example/
  # view is default
  #jaffle_shop:
    #staging:
    #  +materialized: view
    #+materialized: view
sources:
  jaffle_shop:
    +enabled: true


# dont touch below
# can be overridden in model files using the `{{ config(...) }}` macro.
# Full documentation: https://docs.getdbt.com/docs/configuring-models
version: '1.0.0'
config-version: 2
# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
